version: 1
services:
  - type: web
    name: firecrawl-api
    env: docker
    dockerfilePath: ./apps/api/Dockerfile # 确保这个路径是正确的
    dockerContext: ./apps/api
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: firecrawl-redis
          property: connectionString
      - key: REDIS_RATE_LIMIT_URL
        fromService:
          type: redis
          name: firecrawl-redis
          property: connectionString
      - key: PLAYWRIGHT_MICROSERVICE_URL
        value: https://firecrawl-playwright.onrender.com
      # ... 其他环境变量 ...
    buildCommand: docker build -t firecrawl-api ./apps/api
    startCommand: docker run firecrawl-api

  - type: worker
    name: firecrawl-worker
    env: docker
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: ./apps/api
    envVars:
      # ... 环境变量 ...
    buildCommand: docker build -t firecrawl-worker ./apps/api
    startCommand: docker run firecrawl-worker pnpm run workers

  - type: web
    name: firecrawl-playwright
    env: docker
    dockerfilePath: ./apps/playwright-service/Dockerfile
    dockerContext: ./apps/playwright-service
    envVars:
      - key: PORT
        value: 3000
      # ... 其他环境变量 ...
    buildCommand: docker build -t firecrawl-playwright ./apps/playwright-service
    startCommand: docker run -p 3000:3000 firecrawl-playwright

  - type: redis
    name: firecrawl-redis
    ipAllowList: []
    plan: free

# 如果需要数据库，可以取消注释以下部分
# databases:
#   - name: firecrawl-db
#     databaseName: firecrawl
#     user: firecrawl
